### ISSUE TITLE
Question: is there any example of its usage as node dependency?

### ISSUE THREAD

**Issue by fantactuka** [tivac/casperjs-mocharunner#1]
Tried something like `casperjs node_modules/casperjs-mocharunner/bin/index.js integration/sample.js` but didn't work for me

**Comment by mallim** [comment]
Have you tried 

casperjs ./node_modules/casperjs-mocharunner/bin/index.js integration/sample.js ?

Regards
Ian Lim

**Comment by tivac** [comment]
This never went anywhere real, sorry.
